### ISSUE TITLE
Exception when using the search function

### ISSUE THREAD

**Issue by itcotta** [brunoais/phpbbextf_read_other#4]
Getting this exception when trying to use the search function in the forums, any idea what it could be?

`2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'Unexpected $search_kind found: ' in /var/www/servers/localhost/forum/ext/brunoais/readOthersTopics/event/main_listener.php:588
2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: #0 [internal function]: brunoais\readOthersTopics\event\main_listener->search_backend_search_after(Object(phpbb\event\data))
2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /var/www/servers/localhost/forum/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(161): call_user_func(Array, Object(phpbb\event\data))
2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: #2 /var/www/servers/localhost/forum/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'core.search_bac...', Object(phpbb\event\data))
2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: #3 /var/www/servers/localhost/forum/phpbb/event/dispatcher.php(60): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('core.search_bac...', Object(phpbb\event\data))
2016-12-29 13:08:10: (mod_fastcgi.c.2702) FastCGI-stderr: #4 /var/www/servers/localhost/forum/phpbb/event/dispatcher.php(46): phpbb\event\dis in /var/www/servers/localhost/forum/ext/brunoais/readOthersTopics/event/main_listener.php on line 588`

**Comment by brunoais** [comment]
I made a new commit. For the moment, I disabled that method.
I'll need to redo how the search part of this extension works I may end up not even have this method in the future.

**Comment by itcotta** [comment]
yeah the commit solved the issue, thanks!
